<a href="https://colab.research.google.com/github/mehmetsar/modules_and_packages/blob/main/Numpy_notes1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy
NumPy (Numerical Python) bilimsel hesaplamaları hızlı bir şekilde yapmamızı sağlayan bir matematik kütüphanesidir. Numpy’ın temelini numpy dizileri oluşturur. Numpy dizileri python listelerine benzer fakat hız ve işlevsellik açısından python listelerinden daha kullanışlıdır.Ayrıca python listelerinden farklı olarak Numpy dizileri homojen yapıda olmalıdır yani dizi içindeki tüm elemanlar aynı veri tipinden olmalıdır.

1) Numpy kütüphanesinin import edilmesi

In [1]:
import numpy as np

In [2]:
##Numpy dizisinin oluşturulması
#Numpy dizisi ve python listesi oluşturup farklarına göz atalım :
# python list
python_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
# numpy array
numpy_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Python listesi :")
print(python_list)
print("Numpy dizisi :")
print(numpy_array)

Python listesi :
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Numpy dizisi :
[0 1 2 3 4 5 6 7 8 9]


Yukarıdaki örneğe baktığımızda python listesi ve numpy dizileri arasında çok fark olmadığını görüyoruz.Fakat çok boyutlu dizilerle(matrisler ile) çalışma imkanı sağladığı ve python listelerinden daha hızlı olduğu için data science alanında genellikle Numpy kütüphanesi kullanılmaktadır.

Dizinin boyutunu bulmak : ndarray.ndim
.ndim →numpy array nesnesinin boyutunu döndürür.

In [4]:
numpy_array1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(numpy_array1.ndim)
numpy_array2 = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
print(numpy_array2.ndim)

1
2


Dizinin satır ve sütun sayısını bulmak: ndarray.shape
.shape →Numpy array nesnesinin kaç satır ve sütundan oluştuğunu gösteren bir tupple nesnesi döndürür.

In [5]:
numpy_array1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(numpy_array1.shape)
print(numpy_array1.ndim)

(10,)
1


In [6]:
numpy_array2 = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
print(numpy_array2.ndim)
print(numpy_array2.shape)

2
(1, 10)


Dizinin satır ve sütun sayısını değiştirmek : ndarray.reshape()
Numpy array’i yeniden şekillendirmek istediğimizde yani satır ve sütun sayısını değiştirmek istediğimizde reshape() metodunu kullanabiliriz. numpy_array isimli değişkenimizi yeniden şekillendirelim:

In [9]:
numpy_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(numpy_array.reshape(1,10))
print(numpy_array.reshape(10,1))
print(numpy_array.reshape(5,2))
#Not : Orijinal matris ve yeniden şekillendirilen matris aynı sayıda elemana sahip olmalıdır.

[[0 1 2 3 4 5 6 7 8 9]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


np.arange() →Python’daki range() fonksiyonuna benzer. Belirtilen başlangıç değerinden başlayıp, her seferinde adım sayısı kadar arttırarak ,bitiş değerine kadar olan sayıları bulunduran bir numpy dizisi dödürür.
Not: Bitiş değerinin diziye dahil edilmediğine dikkat edelim.
Genel kullanım :
np.arange(başlangıç,bitiş,adım sayısı)
np.arange(bitiş) → bu kullanımda default başlangıç değeri 0 , adım sayısı ise 1 olarak kabul edilir. Yani aslında yukarıda ki formatta ifade edecek olursak np.arange(0,bitiş,1) şeklinde yazabiliriz.

In [10]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Dizinin elemanlarını seçmek
Diziden ihtiyyacımız olan eleman veya elemanları nasıl elde edeceğimize bakalım
Genel kullanım : ndarray[rows,columns]
Not: ndarray[:,:] → buradaki “:” kullanımı tüm satır ve sütunları seçmemizi sağlar.

In [11]:
numpy_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
numpy_array = numpy_array.reshape(5,2)
print(numpy_array)
first_row = numpy_array[0]
first_and_second_rows = numpy_array[0:2]
print(first_row)
print(first_and_second_rows)
first_column = numpy_array[:,0]
first_and_second_column = numpy_array[:,0:2]
print(first_column)
print(first_and_second_column)
selecting_item = numpy_array[3,1]
print(selecting_item)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0 1]
[[0 1]
 [2 3]]
[0 2 4 6 8]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
7


In [ ]:
numpy_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
numpy_array = numpy_array.reshape(5,2)
print(numpy_array)
print(numpy_array[::-1]) #diziyi ters çevirir


In [ ]:
##0 matrisi oluşturmak : np.zeros()
#np.zeros() →Bu fonksiyon belirtilen satır ve sütuna sahip 0'lardan oluşan bir matris döndürür.
print(np.zeros((5,4)))

In [ ]:
#np.ones(): zeros() fonksiyonuna benzer şeklide verilen büyüklükte 1'lerden oluşan bir matris döndürür.
print(np.ones((3,3,3)))

In [ ]:
#Birim matris oluşturmak : np.eye()
#np.eye() → Belirlenen boyutlarda birim matris oluşturmamızı sağlayan fonksiyon.
#4X4 lük birim matris
print(np.eye(4))

In [12]:
#Matrisleri birleştirmek
numpy_array = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
numpy_array = numpy_array.reshape(5,2)
#Satır bazlı birleştirme
print(np.concatenate([numpy_array, numpy_array], axis =0))
#Sütun bazlı birleştirme
print(np.concatenate([numpy_array, numpy_array], axis =1))


[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]
 [0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
