<a href="https://colab.research.google.com/github/mehmetsar/modules_and_packages/blob/main/Numpy_notes2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [ ]:
#sum(toplam), max ve min değerlerini hesaplamak
numpy_array = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
numpy_array = numpy_array.reshape(5,2)
print(numpy_array)
print(numpy_array.max())

print(numpy_array.min())

print(numpy_array.sum())


In [ ]:
#Satırların toplamı
print(numpy_array.sum(axis = 1))
#Sütunların toplamı
print(numpy_array.sum(axis = 0))

In [ ]:
#mean, median, varyans ve standart sapma hesaplamak
numpy_array = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
print(numpy_array.mean())
print(np.median(numpy_array))
print(numpy_array.var())
print(numpy_array.std())

In [ ]:
#Matrislerde aritmetik işlemler
##Matrislerden hatırlayacağımız üzere toplama, çıkarma vb. işlemler yapabilmek için işlem yapılacak
### matrislerin satır ve sütun sayılarının eşit olması gerekiyordu.

numpy_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
numpy_array = numpy_array.reshape(3,3)
#dizimizi 3x3 lük, 2 boyutlu bir matrise dönüştürdük.

print(numpy_array)
print(numpy_array + numpy_array)
print(numpy_array - numpy_array)
print(numpy_array * numpy_array)
print(numpy_array / numpy_array)
print(numpy_array + 5)

In [ ]:
#Özel foksiyonlar ile işlemler
#Numpy toplama, çıkarma gibi basit matematiksel işlemlerin yanında 
#trigonometrik, logaritmik,üstel fonksiyonlar… gibi daha kompleks fonksiyonlarla da çalışma imkanı sağlar.

numpy_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
numpy_array = numpy_array.reshape(3,3)
#dizimizi 3x3 lük, 2 boyutlu bir matrise dönüştürdük.
print(np.sin(numpy_array))
print(np.cos(numpy_array))
print(np.sqrt(numpy_array))  
print(np.exp(numpy_array))
print(np.log(numpy_array))

Matrislerin çarpımı
Bu bölüme ,iki matris çarpılırken ilk matrisin sütun sayısının ikinci matrisin satır sayısına eşit olması gerektiğini hatırlayarak başlayalım

In [3]:
numpy_array = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
numpy_array1 = numpy_array.reshape(5,2)
numpy_array2 = numpy_array.reshape(2,5)
print(np.dot(numpy_array1,numpy_array2))

[[  5   6   7   8   9]
 [ 15  20  25  30  35]
 [ 25  34  43  52  61]
 [ 35  48  61  74  87]
 [ 45  62  79  96 113]]


In [ ]:
#Matrisin transpozu
#Matrisin satırlarını sütun, sütunlarını satır yapma işlemi numpy ile “ .T” yazmak kadar kolay.
numpy_array = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
numpy_array = numpy_array.reshape(5,2)
print(numpy_array)
print(numpy_array.T) 


Numpy bize if-else bloğu kullanmamıza gerek kalmadan belirli bir koşulu sağlayan dizi elemanlarıyla çalışma imkanı sağlar. Klasik numpy_array nesnemizi kullanarak nasıl yapılacağına göz atalım:

In [5]:
numpy_array = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
boolean_array = numpy_array >= 5
print(boolean_array)
# 5 ve 5'ten büyük elemanlar
print(numpy_array[boolean_array])
# 5 ten küçük elemanlar
print(numpy_array<5)
print(numpy_array[numpy_array<5])

[False False False False False  True  True  True  True  True]
[5 6 7 8 9]
[ True  True  True  True  True False False False False False]
[0 1 2 3 4]
