<a href="https://colab.research.google.com/github/mehmetsar/modules_and_packages/blob/main/numpy_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr = np.arange(0,11)  
arr[8]

8

In [2]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [4]:
arr[0:4]=100
arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [5]:
arr[:]=3
arr

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [7]:
arr_copy=arr.copy() # this way provides not to change original array


In [9]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [10]:
arr_2d[0] #returns first row

array([ 5, 10, 15])

In [11]:
arr_2d[2] # returns number 2  row

array([35, 40, 45])

In [12]:
arr_2d[0,2] # row 0, column 2

15

In [13]:
arr_2d[:2] #all rows column 2

array([[ 5, 10, 15],
       [20, 25, 30]])

In [14]:
arr_2d[:2,1:] 

array([[10, 15],
       [25, 30]])