<a href="https://colab.research.google.com/github/mehmetsar/modules_and_packages/blob/main/pandas_dataframe_session2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [8]:
datam = [1,2,3,4,5,6,7,8,9,10]
pd.DataFrame(datam, columns="sayılar")

TypeError: ignored

Index(['var1', 'var2', 'var3'], dtype='object')

In [3]:
mp = np.arange(1,10).reshape((3,3))

In [7]:
df = pd.DataFrame(mp, columns= ["var1", "var2", "var3"])
df

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [10]:
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [11]:
df.shape

(3, 3)

In [12]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)


In [14]:
s1

array([8, 9, 4, 5, 2])

In [15]:
s3

array([6, 5, 6, 5, 2])

In [16]:
mydict = {"var1":s1, "var2": s2, "var3":s3}

In [18]:
df1 = pd.DataFrame(mydict)
df1.head()

var1  var2  var3
0     8     3     6
1     9     3     5
2     4     9     6
3     5     3     5
4     2     8     2

In [20]:
df3 = pd.read_csv("ornek.csv")
df3.head()

a   b     c
0  10  12   3.0
1  11  33  34.0
2  44  51   NaN
3  10  12   4.0
4  11  33  35.0

In [21]:
df3.shape

(15, 3)

In [22]:
df1[1:3]

var1  var2  var3
1     9     3     5
2     4     9     6

In [24]:
df1.head()

var1  var2  var3
0     8     3     6
1     9     3     5
2     4     9     6
3     5     3     5
4     2     8     2

In [25]:
df1.index = ["a", "b","c","d","e"]
df1.head()

var1  var2  var3
a     8     3     6
b     9     3     5
c     4     9     6
d     5     3     5
e     2     8     2

In [27]:
df1["a":"d"] # Burada seçili index dahil numerik indekslemeden farklı olarak

var1  var2  var3
a     8     3     6
b     9     3     5
c     4     9     6
d     5     3     5

In [30]:
np.random.seed(101)
df3 = pd.DataFrame(np.random.randn(5,4), index="a b c d e".split(), columns="w x y z".split())
df3

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [31]:
df3["w"]

a    2.706850
b    0.651118
c   -2.018168
d    0.188695
e    0.190794
Name: w, dtype: float64

In [32]:
type(df3["w"])

pandas.core.series.Series

In [34]:
df3[["w","z"]] # birden fazla farklı sütun çağrılacaksa iki köşeli parantez

w         z
a  2.706850  0.503826
b  0.651118  0.605965
c -2.018168 -0.589001
d  0.188695  0.955057
e  0.190794  0.683509

In [36]:
df3["yepyeni"]=df3["x"]*df3["y"] # yeni sütun oluşturduk
df3

w         x         y         z   yepyeni
a  2.706850  0.628133  0.907969  0.503826  0.570325
b  0.651118 -0.319318 -0.848077  0.605965  0.270806
c -2.018168  0.740122  0.528813 -0.589001  0.391387
d  0.188695 -0.758872 -0.933237  0.955057  0.708208
e  0.190794  1.978757  2.605967  0.683509  5.156577

In [43]:
df3.drop(["yepyeni"],axis=1, inplace=True)
df3

KeyError: ignored

In [44]:
df3

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [45]:
df3.drop(["c"],axis=0)

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [46]:
df3

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [ ]:
# .loc vs .iloc

In [47]:
m = np.random.randint(1,30, size = (10,3))
df4 = pd.DataFrame(m, columns = ["var1","var2","var3"])
df4

var1  var2  var3
0     8    11    21
1    25     8     7
2    15    10    21
3    19    24     8
4     8    16    13
5     1    21    11
6    13    18    25
7    12    20    16
8     2    25     5
9    29    20    19

In [48]:
df4.loc[1]

var1    25
var2     8
var3     7
Name: 1, dtype: int64

In [49]:
df4.iloc[1:4]

var1  var2  var3
1    25     8     7
2    15    10    21
3    19    24     8

In [51]:
df4.index = "a b c d e f g h i j".split()
df4

var1  var2  var3
a     8    11    21
b    25     8     7
c    15    10    21
d    19    24     8
e     8    16    13
f     1    21    11
g    13    18    25
h    12    20    16
i     2    25     5
j    29    20    19

In [54]:
df4.loc["a":"f"]["var2"]

a    11
b     8
c    10
d    24
e    16
f    21
Name: var2, dtype: int64

In [57]:
df4.iloc[1:5]["var2"]

b     8
c    10
d    24
e    16
Name: var2, dtype: int64

In [60]:
df3.iloc[:,[2]]

y
a  0.907969
b -0.848077
c  0.528813
d -0.933237
e  2.605967

In [64]:
df3.iloc[:,2:]

y         z
a  0.907969  0.503826
b -0.848077  0.605965
c  0.528813 -0.589001
d -0.933237  0.955057
e  2.605967  0.683509

In [67]:
df3[df3["w"]>0][["y","z"]]

y         z
a  0.907969  0.503826
b -0.848077  0.605965
d -0.933237  0.955057
e  2.605967  0.683509

In [68]:
df3[(df3["w"]>0) & (df3["y"]>0.5) ]

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
e  0.190794  1.978757  2.605967  0.683509

In [69]:
df3[(df3["w"]>0) | (df3["y"]>0.5) ]


w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509