<a href="https://colab.research.google.com/github/mehmetsar/modules_and_packages/blob/main/pandas_dataframe_session2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [8]:
datam = [1,2,3,4,5,6,7,8,9,10]
pd.DataFrame(datam, columns="sayılar")

TypeError: ignored

Index(['var1', 'var2', 'var3'], dtype='object')

In [3]:
mp = np.arange(1,10).reshape((3,3))

In [7]:
df = pd.DataFrame(mp, columns= ["var1", "var2", "var3"])
df

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [10]:
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [11]:
df.shape

(3, 3)

In [12]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)


In [14]:
s1

array([8, 9, 4, 5, 2])

In [15]:
s3

array([6, 5, 6, 5, 2])

In [16]:
mydict = {"var1":s1, "var2": s2, "var3":s3}

In [18]:
df1 = pd.DataFrame(mydict)
df1.head()

var1  var2  var3
0     8     3     6
1     9     3     5
2     4     9     6
3     5     3     5
4     2     8     2

In [20]:
df3 = pd.read_csv("ornek.csv")
df3.head()

a   b     c
0  10  12   3.0
1  11  33  34.0
2  44  51   NaN
3  10  12   4.0
4  11  33  35.0

In [21]:
df3.shape

(15, 3)

In [22]:
df1[1:3]

var1  var2  var3
1     9     3     5
2     4     9     6

In [24]:
df1.head()

var1  var2  var3
0     8     3     6
1     9     3     5
2     4     9     6
3     5     3     5
4     2     8     2

In [25]:
df1.index = ["a", "b","c","d","e"]
df1.head()

var1  var2  var3
a     8     3     6
b     9     3     5
c     4     9     6
d     5     3     5
e     2     8     2

In [27]:
df1["a":"d"] # Burada seçili index dahil numerik indekslemeden farklı olarak

var1  var2  var3
a     8     3     6
b     9     3     5
c     4     9     6
d     5     3     5

In [30]:
np.random.seed(101)
df3 = pd.DataFrame(np.random.randn(5,4), index="a b c d e".split(), columns="w x y z".split())
df3

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [31]:
df3["w"]

a    2.706850
b    0.651118
c   -2.018168
d    0.188695
e    0.190794
Name: w, dtype: float64

In [32]:
type(df3["w"])

pandas.core.series.Series

In [34]:
df3[["w","z"]] # birden fazla farklı sütun çağrılacaksa iki köşeli parantez

w         z
a  2.706850  0.503826
b  0.651118  0.605965
c -2.018168 -0.589001
d  0.188695  0.955057
e  0.190794  0.683509

In [36]:
df3["yepyeni"]=df3["x"]*df3["y"] # yeni sütun oluşturduk
df3

w         x         y         z   yepyeni
a  2.706850  0.628133  0.907969  0.503826  0.570325
b  0.651118 -0.319318 -0.848077  0.605965  0.270806
c -2.018168  0.740122  0.528813 -0.589001  0.391387
d  0.188695 -0.758872 -0.933237  0.955057  0.708208
e  0.190794  1.978757  2.605967  0.683509  5.156577

In [43]:
df3.drop(["yepyeni"],axis=1, inplace=True)
df3

KeyError: ignored

In [44]:
df3

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [45]:
df3.drop(["c"],axis=0)

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [46]:
df3

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [ ]:
# .loc vs .iloc

In [47]:
m = np.random.randint(1,30, size = (10,3))
df4 = pd.DataFrame(m, columns = ["var1","var2","var3"])
df4

var1  var2  var3
0     8    11    21
1    25     8     7
2    15    10    21
3    19    24     8
4     8    16    13
5     1    21    11
6    13    18    25
7    12    20    16
8     2    25     5
9    29    20    19

In [48]:
df4.loc[1]

var1    25
var2     8
var3     7
Name: 1, dtype: int64

In [49]:
df4.iloc[1:4]

var1  var2  var3
1    25     8     7
2    15    10    21
3    19    24     8

In [51]:
df4.index = "a b c d e f g h i j".split()
df4

var1  var2  var3
a     8    11    21
b    25     8     7
c    15    10    21
d    19    24     8
e     8    16    13
f     1    21    11
g    13    18    25
h    12    20    16
i     2    25     5
j    29    20    19

In [54]:
df4.loc["a":"f"]["var2"]

a    11
b     8
c    10
d    24
e    16
f    21
Name: var2, dtype: int64

In [57]:
df4.iloc[1:5]["var2"]

b     8
c    10
d    24
e    16
Name: var2, dtype: int64

In [60]:
df3.iloc[:,[2]]

y
a  0.907969
b -0.848077
c  0.528813
d -0.933237
e  2.605967

In [64]:
df3.iloc[:,2:]

y         z
a  0.907969  0.503826
b -0.848077  0.605965
c  0.528813 -0.589001
d -0.933237  0.955057
e  2.605967  0.683509

In [67]:
df3[df3["w"]>0][["y","z"]]

y         z
a  0.907969  0.503826
b -0.848077  0.605965
d -0.933237  0.955057
e  2.605967  0.683509

In [68]:
df3[(df3["w"]>0) & (df3["y"]>0.5) ]

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
e  0.190794  1.978757  2.605967  0.683509

In [71]:
df3[(df3["w"]>0.5) | (df3["y"]>0.5) ]


w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
e  0.190794  1.978757  2.605967  0.683509

In [ ]:
# reset index

In [72]:
df3.reset_index() # drop yaptıktan sonra genelde reset index ihtiyacı doğabilir

index         w         x         y         z
0     a  2.706850  0.628133  0.907969  0.503826
1     b  0.651118 -0.319318 -0.848077  0.605965
2     c -2.018168  0.740122  0.528813 -0.589001
3     d  0.188695 -0.758872 -0.933237  0.955057
4     e  0.190794  1.978757  2.605967  0.683509

In [74]:
df3.reset_index(drop=True)

w         x         y         z
0  2.706850  0.628133  0.907969  0.503826
1  0.651118 -0.319318 -0.848077  0.605965
2 -2.018168  0.740122  0.528813 -0.589001
3  0.188695 -0.758872 -0.933237  0.955057
4  0.190794  1.978757  2.605967  0.683509

In [75]:
df3

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [76]:
new_index="CA NY WY OR CO".split()

In [80]:
df3["States"] = new_index

In [81]:
df3.set_index("States", inplace = True)
df3

w         x         y         z
States                                        
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

In [82]:
outside = ['M1', 'M1', 'M1', 'M2', 'M2', 'M2']
inside = [1, 2, 3, 1, 2, 3]
multi_index = list(zip(outside, inside))
multi_index

[('M1', 1), ('M1', 2), ('M1', 3), ('M2', 1), ('M2', 2), ('M2', 3)]

In [84]:
hier_index = pd.MultiIndex.from_tuples(multi_index)
hier_index

MultiIndex([('M1', 1),
            ('M1', 2),
            ('M1', 3),
            ('M2', 1),
            ('M2', 2),
            ('M2', 3)],
           )

In [89]:
df5 = pd.DataFrame(np.random.randn(6,2), index=hier_index, columns = ["A","B"])
df5

A         B
M1 1 -1.467514 -0.494095
   2 -0.162535  0.485809
   3  0.392489  0.221491
M2 1 -0.855196  1.541990
   2  0.666319 -0.538235
   3 -0.568581  1.407338

In [ ]:
df5.loc["M1"]

In [90]:
df5.loc["M1"]
df5.xs("M1")

A         B
1 -1.467514 -0.494095
2 -0.162535  0.485809
3  0.392489  0.221491

In [91]:
df5.xs(("M1", 1))

A   -1.467514
B   -0.494095
Name: (M1, 1), dtype: float64

In [92]:
df = sns.load_dataset("planets")
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [93]:
df.shape

(1035, 6)

In [95]:
df.describe()

number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [96]:
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [97]:
df.iloc[1:5][2:4]

method  number  orbital_period  mass  distance  year
3  Radial Velocity       1          326.03  19.4    110.62  2007
4  Radial Velocity       1          516.22  10.5    119.47  2009

In [98]:
df.iloc[1:5,2:4]


orbital_period   mass
1         874.774   2.21
2         763.000   2.60
3         326.030  19.40
4         516.220  10.50

In [99]:
df.drop(["number"],axis=1) # inplace = True dersen kalıcı siler

method  orbital_period   mass  distance  year
0     Radial Velocity      269.300000   7.10     77.40  2006
1     Radial Velocity      874.774000   2.21     56.95  2008
2     Radial Velocity      763.000000   2.60     19.84  2011
3     Radial Velocity      326.030000  19.40    110.62  2007
4     Radial Velocity      516.220000  10.50    119.47  2009
...               ...             ...    ...       ...   ...
1030          Transit        3.941507    NaN    172.00  2006
1031          Transit        2.615864    NaN    148.00  2007
1032          Transit        3.191524    NaN    174.00  2007
1033          Transit        4.125083    NaN    293.00  2008
1034          Transit        4.187757    NaN    260.00  2008

[1035 rows x 5 columns]

In [101]:
df[(df["mass"]>3) & (df["distance"]>180)]

method  number  orbital_period  mass  distance  year
161  Radial Velocity       2           428.5  15.2    214.00  2009
181  Radial Velocity       2          1022.0   3.4    354.00  2011
245  Radial Velocity       1           471.6  14.0    300.30  2005
396  Radial Velocity       1           647.3   4.0    221.24  2011
563  Radial Velocity       1          4885.0   3.1    189.39  2009
587  Radial Velocity       1           875.5   9.9    352.11  2012
610  Radial Velocity       1           672.1  11.1    289.02  2012
620  Radial Velocity       1           745.7   5.3    307.69  2011